import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Layout.module.css'
import Sidebar from './Sidebar'
import Search from "../assets/search.svg";


const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Skymail</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <Sidebar />
                <main id="main" className={styles.content}>
                    <Search className={styles.search} />
                    {children}
                </main>
            </div>
        </div>

    )
}

export default Layout